version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - postgres
    volumes:
      - ./flyway/sql:/flyway/sql
    command: >
      -url=jdbc:postgresql://pg_db:5432/${POSTGRES_DB}
      -schemas=${FLYWAY_SCHEMAS}
      -user=${POSTGRES_USER}
      -password=${POSTGRES_PASSWORD}
      migrate

  api:
    build:
      context: ./PokemonCardsApi
    container_name: dotnet_api
    ports:
      - "5236:8080"  # hostPort:containerPort
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=pg_db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

  frontend: 
    build:
      context: ./pokemon-cards-frontend
    container_name: react_frontend
    ports: 
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./pokemon-cards-frontend:/app
      - /app/node_modules
    command: ["npm", "start"]
    depends_on:
      - api

volumes:
  pgdata:
